SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS A
LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SEX_UPON_OUTCOME IS NULL
ORDER BY A.DATETIME
LIMIT 3;

--https://programmers.co.kr/learn/courses/30/lessons/59044