SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A
INNER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE SEX_UPON_INTAKE != SEX_UPON_OUTCOME
ORDER BY A.ANIMAL_ID;

--https://programmers.co.kr/learn/courses/30/lessons/59045