WITH RECURSIVE DUMMY AS (
SELECT ROW_NUMBER() OVER(ORDER BY DATETIME)-1 AS HOUR
FROM ANIMAL_OUTS 
LIMIT 24 )

SELECT HOUR , COUNT(ANIMAL_ID) AS COUNT
FROM DUMMY
LEFT JOIN ANIMAL_OUTS
ON HOUR(DATETIME) = DUMMY.HOUR
GROUP BY HOUR
ORDER BY HOUR;

--https://programmers.co.kr/learn/courses/30/lessons/59413